### ISSUE TITLE
Explain the differences among GitHub, Git clone, and Git branch

### ISSUE THREAD

**Issue by jaminhanna** [cs340-24/test#35]
Forks "allow for collaboration even when direct participation is not possible." By forking a project, you get an identical copy of the project as it was when you forked it. Any changes you make to this new repository do not affect the forked (original) repository. In order to update the original repository with changes you made to your new repository (that you got by forking the original), you submit a pull request, in hopes that the pull request will be accepted and therefore merged into the original repository.

Forks are used when a person wants to collaborate on a project but does not have write access to it, and therefore cannot make changes to the original repository. It gives them their own copy of the repository to make changes to, and they can submit a pull request to the original repository to propose that changes they made (to their copy of the original) be merged (incorporated) into the original repository.

Branches give one the ability to do work on a repository in isolation from changes made by others following the branch. When you branch a repository, you break off from the main line of development, and so any changes that you make affect only your newly created branch, and not the master (or main) branch, or whatever branch you branched from, until you decide to merge your changes with that branch, at which point the two branches will both point to the same state of the project, and the branch you created can then be deleted if it is no longer needed.

**Comment by mickidymick** [comment]
Please add a milestone and add the file with the correct answers.

**Comment by jaminhanna** [comment]
[file.md](https://github.com/cs340-24/test/files/14189155/file.md)

**Comment by mickidymick** [comment]
I still need you to push the .md file to the test repo
