### ISSUE TITLE
Explain the differences among GitHub fork, git clone, and git branch

### ISSUE THREAD

**Issue by PiSaucer** [cs340-24/test#36]
GitHub fork copies the current branch (normally main) of a GitHub project. It copies the git repo into your own account for your own purposes or to help the project as a whole.

`git clone` copies the git repo at the current branch (normally main) onto your local machine. This allows you to work on the project in your own environment and IDE.

`git branch` creates a new branch in the current git repo. This allows you to work on a new feature or bug fix without affecting the main branch.

**Comment by mickidymick** [comment]
Please assign yourself to the issue.
