### ISSUE TITLE
Explain the differences among github fork, git clone, and git branch

### ISSUE THREAD

**Issue by smohyud4** [cs340-24/test#39]
Fork - A Github specific operation that allows you to copy a repository and add it to your Github account. Once a repo is forked, you can commit changes to it without affecting the initial repo by submitting a pull request to the owner.

Clone - A way in which you can import a copy of a Github repository to your local machine instead of your Github account.

Branch - A way in which you can work on adding new features without affecting the main branch. This allows developers to work on separate features, and when the changes are ready, they can merge it back onto the main branch.

**Comment by mickidymick** [comment]
Please assign yourself to the issue, add a milestone and add the file with the correct answers.
