### ISSUE TITLE
Explain the differences among github fork, git clone, and git branch

### ISSUE THREAD

**Issue by Silverasdf** [cs340-24/test#8]
GitHub fork is used specifically for GitHub rather than just git. It is used to copy a repo so that you can have ownership over the repo copy. Then, you can modify the repo and do a Pull Request to merge your changes from your copy of the repo to the actual repo.

Git clone is used to create a copy of a repo from a remote source to your local machine. Just like with forking, you can then do pull requests to the remote branch. However, a difference is that you may be the owner of the remote repo, so therefore, you only have to push modifications to the remote (GitHub) repo.

Git branch is typically used when adding a new feature or honing in on something specific in the code. This way, developers can modify a feature branch (that may be less secure) while leaving the main branch untouched. Merging can be done later when the feature is fully developed.

**Comment by mickidymick** [comment]
Please add the file with the correct answers.

**Comment by Silverasdf** [comment]
Done
